# SPDX-FileCopyrightText: 2026 Redcat
# SPDX-License-Identifier: LicenseRef-Redcat-Permission-Only
# Use requires prior written permission from Redcat.

[package]
name = "eve-finality-verifier"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license-file.workspace = true

[dependencies]
alloy-primitives.workspace = true
alloy-rlp.workspace = true
eve-consensus-comet = { path = "../consensus-comet" }
eve-evm = { path = "../execution" }
eve-protocol-config = { path = "../protocol-config" }
eve-state = { path = "../state" }
prost.workspace = true

[dev-dependencies]
ed25519-dalek.workspace = true
prost-types.workspace = true
sha2.workspace = true

[lints]
workspace = true
