// SPDX-FileCopyrightText: 2026 Redcat
// SPDX-License-Identifier: LicenseRef-Redcat-Permission-Only
// Use requires prior written permission from Redcat.

use super::proposal_fixture;
use crate::consensus::{
    approval::{approved_state_block, create_execution_approval},
    signing::{
        open_durable_signer,
        tests::{temporary_fixture, test_key},
    },
};
use eve_state::{Address, U256, development_state_budget};
use eve_storage::{records::development_opaque_record_budget, state::read_state_service};

#[test]
fn valid_revert_is_approved_with_failed_receipt_nonce_fee_and_atomic_rollback() {
    let (_directory, fixture) = temporary_fixture();
    let signer = open_durable_signer(
        &fixture.root.join("signing"),
        fixture.config.clone(),
        test_key(1),
        fixture.service.clone(),
        development_opaque_record_budget(),
    )
    .unwrap();
    // Public-only disposable envelope generated by pinned viem; no private entropy was saved.
    let transaction = hex::decode("02f86d827a6980843b9aca0084b2d05e00830186a09400000000000000000000000000000000000000427b80c001a020d9b589ea8d83d49a6ae15d1dd32742c2145144d97128c831af2a96af13b4b8a07a3168ad9b3e530b375c62fba20392c329121a3fed476fae7ebca65ee196cc81").unwrap();
    let before = read_state_service(&fixture.service).unwrap();
    let approval = create_execution_approval(
        &signer,
        &proposal_fixture(&fixture.config, vec![transaction]),
        &development_state_budget(),
        256 * 1024 * 1024,
    )
    .unwrap();
    let prepared = approved_state_block(&approval);
    let sender: Address = "4E1c6bB3b3e3e95F6310Eb3058560C83580a4c7B".parse().unwrap();
    assert_eq!(prepared.commit.state.accounts[&sender].nonce, 1);
    assert!(
        prepared.commit.state.accounts[&sender].balance
            < before.commit().state.accounts[&sender].balance
    );
    assert_eq!(
        prepared.commit.state.accounts[&Address::with_last_byte(0x42)].balance,
        U256::ZERO
    );
    assert!(
        prepared.commit.state.accounts[&Address::with_last_byte(0x42)]
            .storage
            .is_empty()
    );
    assert_eq!(prepared.commit.block.receipts.len(), 1);
    assert!(prepared.fees.burn > U256::ZERO);
    assert_eq!(
        read_state_service(&fixture.service).unwrap().commit(),
        before.commit()
    );
    assert_eq!(prepared.outcomes.len(), 1);
    assert!(!prepared.outcomes[0].execution.is_success());
}
