# SPDX-FileCopyrightText: 2026 Redcat
# SPDX-License-Identifier: LicenseRef-Redcat-Permission-Only
# Use requires prior written permission from Redcat.

[package]
name = "eve-crypto"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license-file.workspace = true

[dependencies]
ml-dsa.workspace = true
ed25519-dalek.workspace = true
zeroize.workspace = true

[dev-dependencies]
serde.workspace = true
serde_json.workspace = true
hex.workspace = true
tempfile.workspace = true

[lints]
workspace = true
