# SPDX-FileCopyrightText: 2026 Redcat
# SPDX-License-Identifier: LicenseRef-Redcat-Permission-Only
# Use requires prior written permission from Redcat.

[package]
name = "eve-consensus-comet"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license-file.workspace = true

[dependencies]
anyhow.workspace = true
serde_json.workspace = true
base64.workspace = true
hex.workspace = true
prost.workspace = true
prost-types.workspace = true
sha2.workspace = true
ed25519-dalek.workspace = true
ed25519-zebra.workspace = true

[build-dependencies]
prost-build.workspace = true
protoc-bin-vendored.workspace = true
sha2.workspace = true

[dev-dependencies]
anyhow.workspace = true
serde_json.workspace = true
tempfile.workspace = true
hex.workspace = true
sha2.workspace = true

[lints]
workspace = true
