# SPDX-FileCopyrightText: 2026 Redcat
# SPDX-License-Identifier: LicenseRef-Redcat-Permission-Only
# Use requires prior written permission from Redcat.

[package]
name = "eve-storage"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license-file.workspace = true

[dependencies]
rocksdb.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
eve-state = { path = "../../../validator/components/state" }
alloy-primitives.workspace = true
alloy-rlp.workspace = true
sha2.workspace = true
rustix.workspace = true

[dev-dependencies]
alloy-consensus.workspace = true
alloy-eips.workspace = true
k256.workspace = true
eve-evm = { path = "../../../validator/components/execution" }
eve-development-fixtures = { path = "../../../validator/components/development-fixtures" }
eve-finality-verifier = { path = "../../../validator/components/finality-verifier" }
tempfile.workspace = true

[lints]
workspace = true
